export enum ActivityState {
  ACTIVE = 'ACTIVE',
  IDLE = 'IDLE',
  BREAK = 'BREAK',
  OFFLINE = 'OFFLINE',
  LOCKED = 'LOCKED',
  SLEEPING = 'SLEEPING',
  WAITING_FOR_INPUT = 'WAITING_FOR_INPUT'
}

export enum ActivityEventType {
  APPLICATION_FOCUS = 'APPLICATION_FOCUS',
  IDLE_INTERVAL = 'IDLE_INTERVAL',
  SYSTEM_LOCK = 'SYSTEM_LOCK',
  SESSION_START = 'SESSION_START',
  SESSION_END = 'SESSION_END',
  APP_FOCUS_START = 'APP_FOCUS_START',
  APP_FOCUS_END = 'APP_FOCUS_END',
  WEBSITE_FOCUS_START = 'WEBSITE_FOCUS_START',
  WEBSITE_FOCUS_END = 'WEBSITE_FOCUS_END',
  IDLE_START = 'IDLE_START',
  IDLE_END = 'IDLE_END',
  LOCK = 'LOCK',
  UNLOCK = 'UNLOCK',
  SLEEP = 'SLEEP',
  RESUME = 'RESUME',
  HEARTBEAT = 'HEARTBEAT',
  NETWORK_OFFLINE = 'NETWORK_OFFLINE',
  NETWORK_ONLINE = 'NETWORK_ONLINE'
}

export enum BreakReason {
  LUNCH = 'LUNCH',
  PERSONAL = 'PERSONAL',
  MEETING = 'MEETING',
  COFFEE = 'COFFEE',
  OTHER = 'OTHER'
}

export enum ApplicationCategory {
  ALL = 'All',
  DEVELOPMENT = 'Development',
  DESIGN = 'Design',
  COMMUNICATION = 'Communication',
  BROWSERS = 'Browsers',
  PRODUCTIVITY = 'Productivity',
  MARKETING = 'Marketing',
  PROJECT_MANAGEMENT = 'Project Management',
  FILE_MANAGEMENT = 'File Management',
  MEDIA = 'Media',
  OTHER = 'Other'
}

